### ISSUE TITLE
Stuck at 21% loading screen.

### ISSUE THREAD

**Issue by Metazolid** [mikroskeem/radicalaces#6]
First of all a huuuge thanks for doing this, brings me all the way back to my childhood!
I coldn't get past the `could not initialize class org.codehaus.groovy.runtime.invokerhelper` error and changed the gradle wrapper properties to version 6.61 instead of 5.2.1 and got it working that way, but now whenever I start the radicalaces.jar I can't get past the 21% loading screen.
I'm not very code savy so I'm not sure if I unintentionally broke something doing this, it'd be great if you could help me out a little bit.
Thanks!

**Comment by mikroskeem** [comment]
I suppose you're using quite recent Java. I've tested this project only with 8 and 11 iirc, so I'd suggest you to stick with either of those.

**Comment by mikroskeem** [comment]
Latest changes should fix the issue completely. Tested with `openjdk version "14.0.2" 2020-07-14` and moved resources into place where Gradle needs them to be, instead of using symlinks. Latter should aid Windows users since symlinks do not seem to work very well there (vs building on Linux or macOS).

Original assets/code structure is now stored [in a different branch instead]https://github.com/mikroskeem/radicalaces/tree/original).
